sudo: required
dist: trusty
language: php
php:
- 5.5
- 5.6
- 7.0
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
before_install:
- sh ./initTestEnv.sh
- sudo apt-get update -qq
- composer selfupdate
before_script:
- sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5
  mysql-client-5.5 mysql-client-core-5.5;
- sudo apt-get -y -qq autoremove;
- sudo apt-get -y -qq autoclean;
- sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;
- mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE
  magento_integration_tests;';
- mv dev/tests/integration/etc/install-config-mysql.travis.php.dist dev/tests/integration/etc/install-config-mysql.php;
- echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- phpenv rehash;
- echo AUTH_JSON > ~/.composer/auth.json
- "/usr/bin/env php composer.phar install --no-interaction"
script: bin/phing
env:
  global:
  - secure: bB0WZ7WmQ4ULUYGfGhstgWlW66eNoX9XHUNv6vQvprp9ywF+4I77obEUBiLYTEFT547oN1NV7s5h4wv1/eoOnQdXYLxa577lw4QVTuAa9LTKLFYWaE6zKWpHJ8XtNo6iAchBo7g6/mvw/6NEwbW9ziqf+J65QcUnEFIGB/ms/Au/ggW/6nf/J72Jl6JHF/qEEVH0Cfa+15oS8Iv/74+Zz5mcHi85hh03ah6a/7G5gJ2lm/wnUAf7TttSxO+fjhkZ0i6l2QH1Cu18wvzlyNEN9ONSAx1UZFwItMWfjMT54YFS3968znuCK6w6l7JzRqhgYFrjMhchBqOCal57AwwCNbo8QjZT+E1i4BXONU03ep/mMGBWJy4dWcVgIP+sz9MMN3lMofwIzMT1gV7IT+5+5YivAJnRBy3Pe1xjLuKdfgq7DVcDEpNel8t8ZLXMR8lDS6pJKlOsT74kiB9X36/XPg7Dpj2UdVS3zgRhH2Me4mCABrw/jO/JJKpSbBPA1b+3EP5Eq0udBGF/yyY8yQ12eeLm3KQudANCLZ+GHNJbuUW/CME9Ef88fFQBxLu838ThvXvXOeAkTW15rawvsH92VcZoiJ7zC1qsNmrTipFt+0576g53jWlWzVDmUQ9tdmB1kpZ43i3dPFJeQLCG2PE2iGIQZsJiTcZNl0UHzplskfk=
