web:
  build: .
  dockerfile: Dockerfile
  ports:
    - "80:80"
  links:
    - mysql
  volumes:
    - "./build:/var/www/html"

mysql:
  image: mariadb
  ports:
    - "3306:3306"
  volumes:
    - "./test/integration/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
  environment:
    MYSQL_ROOT_PASSWORD: mysql

